name: 'Send To Mantle'
description: "GitHub Action use in conjunction with Linchpin's WordPress Client Support Plugin called Mantle"
inputs:
  mantle-uri:
    description: 'The url of the WordPress site where mantle is installed'
    required: true
  mantle-secret:
    description: 'The secret key that was generated for you during Mantle setup on your WordPress site'
    required: true
  mantle-payload:
    description: 'A JSON String of data to pass to mantle'
    required: true
  soft-fail:
    description: 'Allow for message sending to fail gracefully'
    required: false
outputs:
  response: # id of output
    description: 'The response from Mantle when a POST/PUT/GET is made'
runs:
  using: 'node12'
  main: 'dist/index.js'
